# Generated by Django 5.0.1 on 2024-01-11 21:33

import core.models
import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario_imagem_height_funcionario_imagem_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field='imagem_height', null=True, pixel_densities=[1, 2], upload_to=core.models.get_file_path, verbose_name='Imagem', width_field='imagem_width'),
        ),
    ]
