# Generated by Django 5.0.1 on 2024-01-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recusros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recusros',
            new_name='Recursos',
        ),
    ]
