# Generated by Django 5.0.1 on 2024-01-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_recusros_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='icone',
            field=models.CharField(max_length=16, verbose_name='Ícone'),
        ),
    ]
